version: '3.4'

services:
  apigateway:
    image: apigateway
    restart: always
    build:
      context: ../ApiGateway
      dockerfile: Dockerfile

  appserver:
    image: appserver
    restart: always
    build:
      context: ../client-web-app
      dockerfile: Dockerfile
      
  patientservice:
    image: patientservice
    restart: always
    build:
      context: ../PatientService
      dockerfile: Dockerfile

  mediaservice:
    image: mediaservice
    restart: always
    build:
      context: ../MediaService
      dockerfile: Dockerfile
    volumes:
      - ./media:/app/media

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data   # Volume mapping is not working on Windows for Mongo

volumes:
  mongo_data:
    external: true        # Create a volume using `docker volume create`
                          # Use `docker-compose stop` to let volume persist
