version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 27017:27017
 
  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
